"""Add image_url to interview_templates

Revision ID: bd3d2471527c
Revises: 3b7641878a71
Create Date: 2025-04-12 12:21:34.321318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3d2471527c'
down_revision = '3b7641878a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_templates', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_templates', 'image_url')
    # ### end Alembic commands ### 